/* Generated by tools/genfont.py - do not edit.
 * Sources: tools/font5.py, tools/font16.py, tools/glyphs.txt.
 * Change one of those and re-run `python3 tools/genfont.py --emit`. */

#ifndef _EPD_FONT_DATA_H_
#define _EPD_FONT_DATA_H_

#include <stdint.h>

#define EPD_FONT_5X7     0   /* 5x7 */
#define EPD_FONT_16X24   1   /* 16x24 */
#define EPD_FONT_CJK16   2   /* 16x16 CJK */
#define EPD_FONT_COUNT   3

/* One glyph. `off` indexes its font's bits[], which is column-major with the
 * LSB at the top row and `bpc` bytes per column. `w` is the cell width in
 * pixels and varies within a font: the 16x16 face stores ASCII at 8 px so a
 * string can mix half- and full-width cells on one baseline. */
typedef struct {
    uint16_t cp;
    uint16_t off;
    uint8_t  w;
} epd_glyph_t;

/* `index` is sorted by codepoint, so lookup bisects - see epd_font_find(). */
typedef struct {
    const epd_glyph_t *index;
    uint16_t           count;
    const uint8_t     *bits;
    uint8_t            h;
    uint8_t            bpc;
} epd_font_t;

extern const epd_font_t EPD_FONTS[EPD_FONT_COUNT];

#endif /* _EPD_FONT_DATA_H_ */
